RR_TYPE_SECTION = slice(0, 2)
RR_CLASS_SECTION = slice(2, 4)
RR_TTL_SECTION = slice(4, 8)
RR_RDLENGTH_SECTION = slice(8, 10)
RR_RDATA_SECTION = slice(10, None)
RR_FIXED_LENGTH = 10

MX_PREFERENCE_SECTION = slice(0, 2)

SOA_SERIAL_SECTION_LENGTH = 4
SOA_REFRESH_SECTION_LENGTH = 4
SOA_RETRY_SECTION_LENGTH = 4
SOA_EXPIRE_SECTION_LENGTH = 4
SOA_MINIMUM_SECTION_LENGTH = 4

CAA_FLAGS_SECTION = slice(0, 1)
CAA_TAG_LENGTH_SECTION = slice(1, 2)
CAA_TAG_SECTION = slice(2, None)

