RR_TYPE_SECTION = slice(0, 2)
RR_CLASS_SECTION = slice(2, 4)
RR_TTL_SECTION = slice(4, 8)
RR_RDLENGTH_SECTION = slice(8, 10)
RR_RDATA_SECTION = slice(10, None)
RR_FIXED_LENGTH = 10

MX_PREFERENCE_SECTION = slice(0, 2)